import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.overview': 'Overview',
    'nav.shop': 'Shop',
    'nav.cart': 'Cart',
    'nav.orders': 'My Orders',
    'nav.team': 'My Team',
    'nav.pv': 'PV History',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.logout': 'Log Out',
    'nav.users': 'Users',
    'nav.managers': 'Managers',
    'nav.products': 'Products',
    'nav.inventory': 'Inventory',
    'nav.orderManagement': 'Orders',
    'nav.promotions': 'Promotions',
    'nav.approvals': 'Approvals',
    'nav.accounts': 'Accounts',
    'nav.deals': 'Deals',
    'nav.paymentSettings': 'Payments',
    'nav.switchToUser': 'Switch to User View',
    'nav.switchToAdmin': 'Switch to Admin View',
    'admin.dashboard': 'Admin Dashboard',
    'admin.platformOverview': 'Platform overview and key metrics',
    'admin.totalUsers': 'Total Users',
    'admin.active': 'active',
    'admin.totalPV': 'Total PV in System',
    'admin.pendingOrders': 'Pending Orders',
    'admin.payments': 'Payments (Last 7 days)',
    'admin.systemStatus': 'System Status',
    'admin.operational': 'Operational',
    'admin.welcome': 'Welcome to the Admin Dashboard',
    'admin.welcomeDesc': 'Manage your community platform, approve orders, and oversee all operations from this central hub.',
    'admin.quickActions': 'Quick Actions',
    'admin.approvals': 'Approvals',
    'admin.settings': 'Settings',
    'admin.manageAccountsAction': 'Manage user accounts',
    'admin.uploadProductsAction': 'Upload products via Excel',
    'admin.approvePendingOrdersAction': 'Approve pending orders',
    'admin.verifyPaymentProofsAction': 'Verify payment proofs',
    'admin.configurePaymentMethodsAction': 'Configure payment methods',
    'admin.adjustSystemSettingsAction': 'Adjust system settings',
    'admin.monitorActivityLogsAction': 'Monitor activity logs',
    'user.dashboard': 'Dashboard',
    'user.welcome': 'Welcome back',
    'user.overviewSubtitle': "Here's your community overview",
    'user.totalPV': 'Total PV',
    'user.teamMembers': 'Team Members',
    'user.pvNeeded': 'PV needed',
    'user.recentActivity': 'Recent Activity',
    'user.viewAll': 'View All',
    'user.noActivity': 'No recent activity',
    'user.activeBranches': 'Active Branches',
    'user.progressTo': 'Progress to',
    'user.requiredPV': 'Required PV',
    'user.requiredBranches': 'Required Branches',
    'shop.title': 'Shop',
    'shop.search': 'Search products...',
    'shop.allCategories': 'All Categories',
    'shop.addToCart': 'Add to Cart',
    'shop.outOfStock': 'Out of Stock',
    'shop.pv': 'PV',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders yet',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.items': 'Items',
    'orders.pending': 'Pending',
    'orders.confirmed': 'Confirmed',
    'orders.shipped': 'Shipped',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
    'team.title': 'My Team',
    'team.directRecruits': 'Direct Recruits',
    'team.totalTeam': 'Total Team',
    'team.noMembers': 'No team members yet',
    'team.inviteCode': 'Your Invite Code',
    'team.copyCode': 'Copy Code',
    'team.copied': 'Copied!',
    'pv.title': 'PV History',
    'pv.total': 'Total PV',
    'pv.personal': 'Personal PV',
    'pv.team': 'Team PV',
    'pv.noHistory': 'No PV history yet',
    'profile.title': 'Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.country': 'Country',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'auth.login': 'Log In',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.actions': 'Actions',
    'common.processing': 'Processing...',
    'common.uploading': 'Uploading...',
    'common.adding': 'Adding...',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.inStock': 'In Stock',
    'common.na': 'N/A',
    'common.totalMembers': 'Total Members',
    'common.copyId': 'Copy ID',
    'common.role': 'Role',
    'common.status': 'Status',
    'common.user': 'User',
    'common.admin': 'Admin',
    'common.manager': 'Manager',
    'common.placeOrder': 'Place Order',
    'common.orderNow': 'Order Now',
    'shop.subtitle': 'Purchase products and earn PV points',
    'shop.noProducts': 'No products available in this category',
    'shop.priceNotSet': 'Price not set',
    'shop.unitPrice': 'Unit Price',
    'shop.totalAmount': 'Total Amount',
    'shop.youSave': 'You save',
    'shop.orderPending': 'Your order will be pending until approved by the stockist.',
    'shop.loading': 'Loading products...',
    'shop.notAvailable': 'Not available',
    'shop.onlyLeft': 'Only {n} left',
    'shop.addedToCart': '{qty}x {name} added to cart!',
    'shop.failedAddToCart': 'Failed to add to cart',
    'shop.priceNotAvailable': 'Price not available for your country',
    'shop.productNotAvailableCountry': 'Product not available in your country',
    'shop.onlyUnitsAvailable': 'Only {available} units available (need {needed} including {free} free)',
    'shop.failedReserveStock': 'Failed to reserve stock: {message}',
    'shop.orderPlacedSuccess': 'Order placed successfully! Order #{orderNumber} is pending approval.',
    'shop.freeItemsIncludedSuffix': ' ({n} free items included!)',
    'shop.failedPlaceOrder': 'Failed to place order',
    'shop.addMoreToGetFree': 'Add {n} more to get {free} free!',
    'shop.freeItemsIncluded': '+{n} free item(s) included!',
    'shop.quantity': 'Quantity',
    'shop.available': '{n} available',
    'shop.pvPerUnit': '{pv} PV per unit',
    'shop.totalPVLabel': 'Total PV:',
    'shop.freeItemsLabel': 'Free items:',
    'cart.subtitle': 'Review and checkout your selected items',
    'cart.emptySubtitle': 'Start shopping to add products to your cart',
    'cart.orderSummary': 'Order Summary',
    'cart.freeItems': 'Free Items',
    'cart.proceedCheckout': 'Proceed to Checkout',
    'cart.loading': 'Loading cart...',
    'cart.failedUpdateQty': 'Failed to update quantity',
    'cart.itemRemoved': 'Item removed from cart',
    'cart.failedRemoveItem': 'Failed to remove item',
    'cart.priceNotAvailableFor': 'Price not available for {name}',
    'cart.failedSaveOrderItems': 'Failed to save order items: {message}',
    'cart.orderPlacedSuccessSimple': 'Order {orderNumber} placed successfully!',
    'cart.itemsCount': 'Items ({n})',
    'cart.unitLabel': 'Unit:',
    'cart.checkoutModalTitle': 'Checkout',
    'cart.orderSummaryWithCount': 'Order Summary ({n} items)',
    'cart.freeShort': '+{n} free',
    'cart.totalCount': '({n} total)',
    'orders.submitPaymentProof': 'Submit Payment Proof',
    'orders.paymentProofSubmitted': 'Payment Proof Submitted',
    'orders.adminNotes': 'Admin Notes',
    'orders.totalOrders': 'Total Orders',
    'orders.totalAmount': 'Total Amount',
    'orders.awaitingPayment': 'Awaiting Payment',
    'orders.subtitle': 'Track your order status and history',
    'orders.filterAll': 'All',
    'orders.filterAwaiting': 'Awaiting',
    'orders.completed': 'Completed',
    'orders.rejected': 'Rejected',
    'orders.noStatusOrders': 'No {status} orders',
    'orders.orderNumberLabel': 'Order #{number}',
    'orders.itemsCountLabel': '{n} items',
    'orders.statusApproved': 'Approved',
    'orders.qtyLabel': 'Qty: {n}',
    'orders.freeSuffix': ' (+{n} free)',
    'orders.each': 'each',
    'orders.pvValue': 'PV Value',
    'orders.rejectionReason': 'Rejection Reason:',
    'orders.pendingApprovalMsg': 'Your order is pending approval by the stockist.',
    'orders.approvedReserveMsg': 'Your order has been approved and stock has been reserved. Please send payment and submit proof.',
    'orders.refOrderNumber': 'Ref: Order #{number}',
    'orders.sendPaymentTo': 'Send payment to',
    'orders.referenceOrderNumber': 'Reference: Order #{number}',
    'orders.paymentBeingVerifiedMsg': 'Your payment proof has been submitted and is being verified by the admin.',
    'orders.submittedOn': 'Submitted on {date}',
    'orders.orderComplete': 'Order Complete!',
    'orders.paymentVerifiedMsg': 'Your payment has been verified and your PV points have been added to your account.',
    'orders.orderNumberColon': 'Order Number:',
    'orders.itemsColon': 'Items:',
    'orders.paymentInstructionsTitle': 'Payment Instructions',
    'orders.transactionDetailsLabel': 'Transaction Details / Notes (Optional)',
    'orders.transactionPlaceholder': 'Enter transaction ID, confirmation number, or any other notes...',
    'orders.paymentScreenshotLabel': 'Payment Screenshot *',
    'orders.changeScreenshot': 'Change Screenshot',
    'orders.uploadScreenshot': 'Upload Payment Screenshot',
    'orders.uploadScreenshotHint': 'Please upload a clear screenshot of your e-transfer confirmation',
    'orders.paymentSubmittedToast': 'Payment proof submitted successfully! You will be notified once it is verified.',
    'orders.failedSubmitPayment': 'Failed to submit payment proof',
    'orders.paymentProofSubmittedMsg': 'Your payment proof for order {orderNumber} has been submitted and is awaiting verification.',
    'common.unknownProduct': 'Unknown Product',
    'profile.subtitle': 'Manage your personal information and preferences',
    'profile.accountInfo': 'Account Information',
    'profile.emailCantChange': 'Email cannot be changed',
    'profile.memberSince': 'Member Since',
    'profile.deliveryAddress': 'Delivery Address',
    'profile.deliveryAddressDesc': 'This address will be used for product delivery when you place orders.',
    'profile.streetAddress': 'Street Address',
    'profile.apartment': 'Apartment, Suite, etc. (Optional)',
    'profile.city': 'City',
    'profile.stateProvince': 'State / Province',
    'profile.postalCode': 'Postal Code',
    'profile.importantNote': 'Important Note:',
    'profile.countryChangeWarning': "Changing your country will affect which products you can order and the currency used for transactions. This is useful if you travel or relocate to a different country.",
    'profile.uploadPhoto': 'Click camera to upload',
    'profile.maxSize': 'Max 5MB, JPG/PNG/GIF',
    'profile.selectCountry': 'Select a country',
    'profile.currencyNote': "Products will be shown in this currency and you'll order from this country's inventory.",
    'profile.pageTitle': 'Profile Settings',
    'profile.phoneNumber': 'Phone Number',
    'profile.countryColon': 'Country:',
    'profile.currencyColon': 'Currency:',
    'profile.dangerZone': 'Danger Zone',
    'profile.deleteAccountTitle': 'Delete your account',
    'profile.deleteAccountDesc': 'Permanently remove your account and all associated data. This action cannot be undone.',
    'profile.deleteAccountBtn': 'Delete Account',
    'profile.changePassword': 'Change Password',
    'profile.changePasswordDesc': 'Update the password you use to sign in.',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.updatePasswordBtn': 'Update Password',
    'profile.passwordUpdated': 'Password updated successfully.',
    'profile.passwordMismatch': "New passwords don't match.",
    'profile.passwordTooShort': 'Password must be at least 6 characters.',
    'profile.currentPasswordIncorrect': 'Current password is incorrect.',
    'profile.areYouSure': 'Are you absolutely sure?',
    'profile.deleteWarning1': 'Your profile and PV history will be permanently deleted',
    'profile.deleteWarning2': 'Your team members will be unlinked from your account',
    'profile.deleteWarning3': 'Any pending orders will be affected',
    'profile.deleteWarning4': 'This action is irreversible',
    'profile.typeConfirmPrefix': 'Type',
    'profile.typeConfirmSuffix': 'to confirm',
    'profile.deletePlaceholder': 'Type DELETE here...',
    'profile.deletingAccount': 'Deleting account...',
    'profile.permanentlyDelete': 'Permanently delete my account',
    'profile.selectImageFile': 'Please select an image file',
    'profile.imageTooLarge': 'Image must be less than 5MB',
    'profile.photoUpdated': 'Profile photo updated!',
    'profile.failedUploadImage': 'Failed to upload image',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.failedUpdate': 'Failed to update profile',
    'profile.failedDeleteAccount': 'Failed to delete account',
    'profile.notAuthenticated': 'Not authenticated',
    'team.subtitle': 'Your direct referrals and their progress',
    'team.referralLink': 'Your Referral Link',
    'team.shareIdInfo': 'Share your user ID with new members so they can add you as their referrer',
    'team.noMembersSubtitle': 'Start building your team by sharing your referral link with new members',
    'admin.userManagement': 'User Management',
    'admin.manageUsers': 'Manage all platform users',
    'admin.searchUsers': 'Search users by name or email...',
    'admin.orderProcessing': 'Order Processing Workflow',
    'admin.paymentSubmitted': 'Payment Submitted',
    'admin.verifyPayment': 'Verify payment proof. Confirm or reject.',
    'admin.loadingPending': 'Loading pending accounts...',
    'admin.loadingOrders': 'Loading orders...',
    'admin.loadingCodes': 'Loading codes...',
    'admin.loadingTeam': 'Loading team management...',
    'admin.loadingInventory': 'Loading inventory...',
    'admin.confirmRejection': 'Confirm Rejection',
    'admin.addManager': 'Add Manager',
    'admin.editPermissions': 'Edit Permissions',
    'admin.fullAccess': 'Full Access',
    'admin.addProduct': 'Add New Product',
    'admin.editProduct': 'Edit Product',
    'admin.uploadImage': 'Upload Image',
    'admin.editPromotion': 'Edit Promotion',
    'admin.createPromotion': 'Create Promotion',
    'admin.createFirstDeal': 'Create your first "Buy X Get Y Free" deal',
    'admin.buyXGetYFree': 'Create "Buy X Get Y Free" deals for products',
    'admin.expired': 'Expired',
    'admin.pause': 'Pause',
    'admin.activate': 'Activate',
    'admin.addInventory': 'Add Product Inventory',
    'admin.updating': 'Updating...',
    'admin.productManagementTitle': 'Product Management',
    'admin.productManagementSubtitle': 'Manage products and PV values',
    'admin.importExcel': 'Import Excel',
    'admin.importing': 'Importing...',
    'admin.deleteSelected': 'Delete Selected ({n})',
    'admin.productName': 'Product Name',
    'admin.productType': 'Product Type',
    'admin.pvValue': 'PV Value',
    'admin.priceCAD': 'Price (CAD)',
    'admin.productImage': 'Product Image',
    'admin.or': 'or',
    'admin.enterImageUrl': 'Enter Image URL',
    'admin.description': 'Description',
    'admin.englishTranslationOptional': 'English translation (optional)',
    'admin.imagePreview': 'Image Preview:',
    'admin.activeProduct': 'Active Product',
    'admin.select': 'Select',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.productsDeleted': '{n} product(s) deleted',
    'admin.productsDeleteFailed': '{failed} failed, {deleted} deleted',
    'admin.failedUpdateProduct': 'Failed to update product',
    'admin.productUpdated': 'Product updated successfully',
    'admin.productNameRequired': 'Product name is required',
    'admin.failedUpdateMatchingProduct': 'Failed to update matching product',
    'admin.productUpdatedLatest': 'Product updated with latest information',
    'admin.failedAddProduct': 'Failed to add product',
    'admin.productAdded': 'Product added successfully',
    'admin.noValidProductsExcel': 'No valid products found in Excel file. Please ensure columns are named: Product Name, Type, PV, Description',
    'admin.processedProducts': 'Processed {n} product(s) with duplicate matching and update logic',
    'admin.errorProcessingExcel': 'Error processing Excel file',
    'admin.failedDeleteProduct': 'Failed to delete product',
    'admin.productDeleted': 'Product deleted',
    'admin.productNameEnglish': 'Product Name (English)',
    'admin.productTypeEnglish': 'Product Type / Category (English)',
    'admin.descriptionEnglish': 'Description (English)',
    'admin.optional': 'Optional',
    'admin.upload': 'Upload',
    'admin.enterUrl': 'Enter URL',
    'accounts.title': 'Account Approvals',
    'accounts.subtitle': 'Review and approve new account registrations',
    'accounts.requireApproval': 'Require Approval',
    'accounts.requireApprovalOnDesc': 'New users must be approved before signing in',
    'accounts.requireApprovalOffDesc': 'New users are auto-approved on registration',
    'accounts.approvalEnabledToast': 'Account approval is now required for new registrations.',
    'accounts.approvalDisabledToast': 'Account approval is no longer required. New users will be auto-approved.',
    'accounts.failedUpdateApprovalSetting': 'Failed to update approval setting',
    'accounts.accountApprovedTitle': 'Account Approved!',
    'accounts.accountApprovedMsg': 'Your account has been approved. You can now sign in and start your wellness journey with Life Changers.',
    'accounts.accountApprovedToast': 'Account approved successfully!',
    'accounts.failedApproveAccount': 'Failed to approve account',
    'accounts.registrationNotApprovedTitle': 'Account Registration Not Approved',
    'accounts.registrationNotApprovedMsg': 'Your account registration was not approved. Reason: {reason}',
    'accounts.accountRejectedToast': 'Account rejected.',
    'accounts.failedRejectAccount': 'Failed to reject account',
    'accounts.noPendingAccounts': 'No pending accounts to review',
    'accounts.referredBy': 'Referred By',
    'accounts.registrationDate': 'Registration Date',
    'accounts.none': 'None',
    'accounts.approve': 'Approve',
    'accounts.reject': 'Reject',
    'accounts.rejectAccountTitle': 'Reject Account',
    'accounts.rejectReasonPrefix': 'Please provide a reason for rejecting',
    'accounts.rejectReasonSuffix': "'s account:",
    'accounts.rejectionReasonLabel': 'Rejection Reason*',
    'accounts.rejectionPlaceholder': 'Example: Incomplete information, suspicious activity, duplicate account...',
    'um.pv': 'PV',
    'um.demote': 'Demote',
    'um.promote': 'Promote',
    'um.apply': 'Apply',
    'um.confirmDelete': 'Confirm Delete',
    'um.deleting': 'Deleting...',
    'um.pvAmountPlaceholder': 'PV Amount (+ or -)',
    'um.deleteConfirmPrefix': 'Are you sure you want to permanently delete',
    'um.deleteConfirmSuffix': "'s account? This will remove all their data and cannot be undone.",
    'um.invalidPvAmount': 'Please enter a valid PV amount',
    'um.failedAdjustPv': 'Failed to adjust PV',
    'um.pvAdjusted': 'PV adjusted successfully',
    'um.failedUpdateRole': 'Failed to update user role',
    'um.userPromoted': 'User promoted successfully',
    'um.userDemoted': 'User demoted successfully',
    'um.failedDeleteUser': 'Failed to delete user',
    'um.userDeleted': 'User account deleted successfully',
    'mgr.title': 'Team Management',
    'mgr.subtitle': 'Assign people to manage orders, inventory, and more',
    'mgr.searchManagers': 'Search managers...',
    'mgr.masterBadge': 'MASTER',
    'mgr.permissionsCount': '{n} permissions',
    'mgr.fullAdminLabel': 'Full Admin',
    'mgr.fullAdminDesc': 'Has access to all features.',
    'mgr.permissionsLabel': 'Permissions',
    'mgr.noPermissionsAssigned': 'No permissions assigned',
    'mgr.promoteToAdmin': 'Promote to Admin',
    'mgr.demoteToManager': 'Demote to Manager',
    'mgr.remove': 'Remove',
    'mgr.noManagersFound': 'No managers found',
    'mgr.selectUser': 'Select User',
    'mgr.chooseUser': 'Choose a user...',
    'mgr.warningLabel': 'Warning:',
    'mgr.warningRemoveAll': 'Removing all permissions will demote this person back to a regular user.',
    'mgr.accessRestricted': 'Access Restricted',
    'mgr.accessRestrictedDesc': 'Only the master account can manage team permissions.',
    'mgr.pleaseSelectUserPermission': 'Please select a user and at least one permission.',
    'mgr.failedAddManager': 'Failed to add manager',
    'mgr.permissionsUpdated': 'Permissions updated successfully',
    'mgr.failedUpdatePermissions': 'Failed to update permissions',
    'mgr.managerRemoved': 'Manager removed successfully',
    'mgr.failedRemoveManager': 'Failed to remove manager',
    'mgr.userPromotedAdmin': 'User promoted to admin',
    'mgr.failedPromoteAdmin': 'Failed to promote to admin',
    'mgr.adminDemotedManager': 'Admin demoted to manager',
    'mgr.failedDemoteAdmin': 'Failed to demote admin',
    'perm.manage_orders.label': 'Manage Orders',
    'perm.manage_orders.desc': 'View, approve, reject, and update order statuses',
    'perm.manage_inventory.label': 'Manage Inventory',
    'perm.manage_inventory.desc': 'View and update stock levels',
    'perm.manage_users.label': 'Manage Users',
    'perm.manage_users.desc': 'View and edit user profiles',
    'perm.manage_accounts.label': 'Manage Accounts',
    'perm.manage_accounts.desc': 'Approve or reject new account registrations',
    'perm.manage_products.label': 'Manage Products',
    'perm.manage_products.desc': 'Add, edit, and deactivate products',
    'perm.manage_promotions.label': 'Manage Promotions',
    'perm.manage_promotions.desc': 'Manage product promotions and deals',
    'ps.failedLoad': 'Failed to load payment settings',
    'ps.paymentMethodRemoved': 'Payment method removed',
    'ps.failedRemovePaymentMethod': 'Failed to remove payment method',
    'ps.presetExists': '"{label}" already exists for this country',
    'ps.paymentLabelRequired': 'Payment label is required for all methods',
    'ps.settingsSavedFor': 'Payment settings saved for {country}',
    'ps.failedSaveSettings': 'Failed to save payment settings',
    'ps.globalSettingsSaved': 'Global payment settings saved',
    'ps.failedSaveGlobalSettings': 'Failed to save global settings',
    'ps.loadingSettings': 'Loading payment settings...',
    'ps.title': 'Payment Settings',
    'ps.subtitle': 'Configure payment methods and contact info for each country',
    'ps.globalDefaults': 'Global Default Settings',
    'ps.globalDefaultsDesc': 'These are used as fallback when no country-specific payment info is configured.',
    'ps.defaultAdminEmail': 'Default Admin Email',
    'ps.defaultPaymentInstructions': 'Default Payment Instructions',
    'ps.generalInstructionsPlaceholder': 'General payment instructions...',
    'ps.saveGlobalSettings': 'Save Global Settings',
    'ps.filterByContinent': 'Filter by continent:',
    'ps.allCountries': 'All Countries ({n})',
    'ps.activeMethods': '{n} active method(s)',
    'ps.noMethods': 'No methods',
    'ps.quickAdd': 'Quick add:',
    'ps.custom': 'Custom',
    'ps.noMethodsConfigured': 'No payment methods configured. Add one above or users will see the global default.',
    'ps.methodNumber': 'Method #{n}',
    'ps.unsaved': 'Unsaved',
    'ps.deactivate': 'Deactivate',
    'ps.activate': 'Activate',
    'ps.remove': 'Remove',
    'ps.paymentLabel': 'Payment Label *',
    'ps.paymentLabelPlaceholder': 'e.g. Interac e-Transfer, MTN Mobile Money',
    'ps.recipientName': 'Recipient Name',
    'ps.recipientNamePlaceholder': 'Name of recipient',
    'ps.recipientContact': 'Recipient Contact (email, phone, or account #)',
    'ps.recipientContactPlaceholder': 'e.g. admin@email.com or +237 6XX XXX XXX',
    'ps.methodKey': 'Method Key',
    'ps.methodKeyPlaceholder': 'e.g. e_transfer, mtn_mobile_money',
    'ps.paymentInstructions': 'Payment Instructions',
    'ps.paymentInstructionsPlaceholder': 'Specific instructions for this payment method...',
    'ps.saveCountrySettings': 'Save {country} Settings',
    'inv.title': 'Inventory Management',
    'inv.subtitle': 'Manage product stock levels',
    'inv.setDefaultStock': 'Set Default Stock',
    'inv.addInventory': 'Add Inventory',
    'inv.searchProducts': 'Search products...',
    'inv.noItemsFound': 'No inventory items found',
    'inv.product': 'Product',
    'inv.available': 'Available',
    'inv.reserved': 'Reserved',
    'inv.lowStock': 'Low Stock',
    'inv.addProductInventoryTitle': 'Add Product Inventory',
    'inv.selectProduct': 'Select a product',
    'inv.stockAvailable': 'Stock Available',
    'inv.lowStockThreshold': 'Low Stock Alert Threshold',
    'inv.refreshStock': 'Refresh Stock',
    'inv.reservedHeldByOrders': 'Reserved (held by pending orders)',
    'inv.resetToZero': 'Reset to 0',
    'inv.reservedHint': "Only lower this if orders were rejected/cancelled and stock wasn't released correctly.",
    'inv.availableForSale': 'Available for sale',
    'inv.updateAcrossProducts': 'Update stock levels across all products.',
    'inv.overwriteWarning': 'This will overwrite current stock levels for the selected scope.',
    'inv.updating': 'Updating...',
    'inv.updateExistingStock': 'Update Existing Stock',
    'inv.initializing': 'Initializing...',
    'inv.initializeAllProducts': 'Initialize All Products',
    'inv.inventoryAdded': 'Inventory added successfully',
    'inv.failedAddInventory': 'Failed to add inventory',
    'inv.stockReservedError': 'Stock available cannot be less than reserved. Lower "Reserved" or raise "Stock Available" first.',
    'inv.inventoryUpdated': 'Inventory updated successfully',
    'inv.failedUpdateInventory': 'Failed to update inventory',
    'inv.stockUpdatedToAll': 'Stock updated to {n} for all products',
    'inv.initializedRecords': 'Initialized {n} inventory records with {qty} stock each',
    'inv.failedInitializeStock': 'Failed to initialize stock',
    'promo.title': 'Product Promotions',
    'promo.newPromotion': 'New Promotion',
    'promo.pleaseAllFields': 'Please fill in all required fields. Buy and free quantities must be at least 1.',
    'promo.failedCreate': 'Failed to create promotion',
    'promo.selectedProductFallback': 'Selected product',
    'promo.created': 'Promotion created successfully',
    'promo.failedUpdate': 'Failed to update promotion',
    'promo.updated': 'Promotion updated successfully',
    'promo.failedCancel': 'Failed to cancel promotion',
    'promo.cancelled': 'Promotion cancelled and ended',
    'promo.failedDelete': 'Failed to delete promotion',
    'promo.deleted': 'Promotion deleted',
    'promo.noPromotionsYet': 'No promotions yet',
    'promo.titleLabel': 'Title',
    'promo.titlePlaceholder': 'e.g., Buy 3 Get 1 Free',
    'promo.buyQuantity': 'Buy Quantity',
    'promo.buyQuantityHint': 'Customer must buy this many',
    'promo.freeQuantity': 'Free Quantity',
    'promo.freeQuantityHint': 'They get this many for free',
    'promo.startsAt': 'Starts At',
    'promo.endsAt': 'Ends At',
    'promo.previewText': 'Preview: Buy {buy}, get {free} free (customer pays for {buy}, receives {total} total)',
    'promo.payReceiveTotal': 'Pay for {buy}, receive {total} total',
    'promo.starts': 'Starts:',
    'promo.ends': 'Ends:',
    'common.close': 'Close',
    'om.failedLoadUserHistory': 'Failed to load user order history',
    'om.cannotApproveStock': 'Cannot approve: not enough stock available for {product}.',
    'om.orderApprovedToast': 'Order approved. Stock reserved. User has been notified to submit payment.',
    'om.failedApproveOrder': 'Failed to approve order',
    'om.ordersMergedToast': '{n} order(s) merged into {orderNumber}. Now approving...',
    'om.failedMergeOrders': 'Failed to merge orders',
    'om.orderRejectedToast': 'Order rejected. User has been notified.',
    'om.failedRejectOrder': 'Failed to reject order',
    'om.paymentVerifiedToast': 'Payment verified and order completed! User has been notified.',
    'om.failedVerifyPayment': 'Failed to verify payment',
    'om.paymentRejectedToast': 'Payment proof rejected. User has been notified to resubmit.',
    'om.failedRejectPayment': 'Failed to reject payment',
    'om.statusChangedToast': 'Order status changed to "{status}".',
    'om.failedChangeStatus': 'Failed to change status',
    'om.promotionAppliedTitle': 'Promotion Applied!',
    'om.promotionAppliedMsg': 'You qualified for a promotion on {product}! {n} free item(s) added to order {orderNumber}.',
    'om.orderApprovedTitle': 'Order Approved - Payment Required',
    'om.orderApprovedMsg': 'Your order {orderNumber} has been approved. Please send payment to {email} and submit your payment proof.',
    'om.orderRejectedNotifTitle': 'Order Rejected',
    'om.orderRejectedMsg': 'Your order {orderNumber} has been rejected. Reason: {reason}',
    'om.paymentVerifiedTitle': 'Payment Verified - Order Complete!',
    'om.paymentVerifiedMsg': 'Your payment for order {orderNumber} has been verified. You earned {pv} PV!',
    'om.paymentRejectedTitle': 'Payment Proof Rejected',
    'om.paymentRejectedMsg': 'Your payment proof for order {orderNumber} was rejected. Reason: {reason}. Please submit a new payment proof.',
    'om.statusUpdatedTitle': 'Order Status Updated',
    'om.statusUpdatedMsg': 'Your order {orderNumber} status has been changed to: {status}.',
    'om.title': 'Order Management',
    'om.subtitle': 'Review and approve customer orders',
    'om.awaitingConfirmationBanner': '{n} order(s) awaiting payment confirmation',
    'om.notShownInPendingFilter': ' (not shown in the current "Pending" filter)',
    'om.viewArrow': 'View',
    'om.workflowTitle': 'Order Processing Workflow',
    'om.step1Desc': 'User submits order. Review stock and approve/reject.',
    'om.step2Desc': 'Stock reserved. User sends payment to admin email.',
    'om.step4Desc': 'Payment verified. PVs allocated to user.',
    'om.workflowImportantNote': 'Important: Approving an order reserves stock and sends your email as the payment address. PVs are ONLY allocated when you verify payment.',
    'om.noOrdersFoundTitle': 'No Orders Found',
    'om.noPendingOrders': 'No pending orders at the moment.',
    'om.noAwaitingPaymentOrders': 'No orders awaiting payment.',
    'om.noCompletedOrders': 'No completed orders yet.',
    'om.noOrdersSystem': 'No orders in the system yet. Orders will appear here once users start shopping.',
    'om.searchOrdersPlaceholder': 'Search orders...',
    'om.allStatus': 'All Status ({n})',
    'om.noOrdersFoundSimple': 'No orders found',
    'om.orderNumberCol': 'Order #',
    'om.customer': 'Customer',
    'om.products': 'Products',
    'om.viewAllOrdersFromUser': 'View all orders from this user',
    'om.proof': 'Proof',
    'om.view': 'View',
    'om.verify': 'Verify',
    'om.changeStatus': 'Change Status',
    'om.orderDetailsTitle': 'Order Details',
    'om.orderNumberLabel': 'Order Number',
    'om.orderItems': 'Order Items',
    'om.orderDateLabel': 'Order Date',
    'om.noAddressWarning': 'Warning: Customer has not provided a delivery address yet. Please contact them to update their profile before shipping.',
    'om.paymentProof': 'Payment Proof',
    'om.loadingProof': 'Loading proof...',
    'om.clickToViewFull': 'Click image to view full size',
    'om.submittedLabel': 'Submitted:',
    'om.customerNotesLabel': 'Customer Notes:',
    'om.verifiedLabel': 'Verified:',
    'om.rejectionReasonLabel': 'Rejection Reason',
    'om.orderWord': 'Order',
    'om.fromWord': 'from',
    'om.otherPendingOrdersHeading': '{n} other pending order(s) from this user',
    'om.selectOrdersToMerge': 'Select orders below to merge them into a single combined order before approving.',
    'om.deselectAll': 'Deselect all',
    'om.selectAll': 'Select all',
    'om.combinedTotalAfterMerge': 'Combined total after merge:',
    'om.adminNotesOptional': 'Admin Notes (Optional)',
    'om.addNotesApprovalPlaceholder': 'Add any notes about this approval...',
    'om.mergeAndApprove': 'Merge ({n} orders) & Approve',
    'om.approveThisOrderOnly': 'Approve This Order Only',
    'om.rejectOrderTitle': 'Reject Order',
    'om.rejectReasonPromptPrefix': 'Please provide a reason for rejecting order',
    'om.rejectReasonPlaceholder': 'Explain why this order is being rejected...',
    'om.internalNotesPlaceholder': 'Add any internal notes...',
    'om.verifyPaymentTitle': 'Verify Payment',
    'om.paymentNotesFromCustomer': 'Payment Notes from Customer',
    'om.paymentScreenshotPlain': 'Payment Screenshot',
    'om.verifyImportantNote': 'Important: Please verify that the payment amount matches the order total and that the payment has been received before confirming.',
    'om.verifyAndComplete': 'Verify Payment & Complete Order',
    'om.rejectPaymentProofTitle': 'Reject Payment Proof',
    'om.rejectPaymentReasonPrompt': 'Please provide a reason for rejecting the payment proof for order',
    'om.rejectPaymentPlaceholder': "Example: Payment screenshot is unclear, amount doesn't match, payment not received...",
    'om.rejectPaymentProofBtn': 'Reject Payment Proof',
    'om.changeOrderStatusTitle': 'Change Order Status',
    'om.currentStatus': 'Current Status',
    'om.newStatus': 'New Status',
    'om.statusChangeNote': 'Note: Manually changing status will not trigger stock or PV adjustments. Use the normal approve/verify workflow for those.',
    'om.updateStatusBtn': 'Update Status',
    'om.orderHistoryTitle': 'Order History - {name}',
    'om.totalOrdersCount': '{n} total order(s)',
    'om.totalSpentLabel': 'Total Spent: {currency} {amount}',
    'om.noOrdersForUser': 'No orders found for this user',
    'om.paidLabel': 'Paid',
    'om.approveOrderTitle': 'Approve Order',
    'notif.newAccountRequestTitle': 'New Account Approval Request',
    'notif.newAccountRequestMsg': '{name} ({email}) has registered and is waiting for approval.',
    'notif.newPromotionTitle': 'New Promotion Available',
    'notif.newPromotionMsg': '{label} is now active for {product}.',
    'notif.newOrderPlacedTitle': 'New Order Placed',
    'notif.newOrderPlacedMsg': 'Order #{orderNumber} from {userName} requires approval',
    'notif.orderReceivedTitle': 'Order Received',
    'notif.orderReceivedMsg': 'Your order #{orderNumber} has been received and is pending approval.',
    'notif.paymentSubmittedAdminMsg': 'Order #{orderNumber} - {userName} submitted payment proof',
    'promo.pageTitle': 'Promotions',
    'promo.manageDeals': 'Manage product deals',
    'promo.pleaseAllFieldsSimple': 'Please fill in all required fields.',
    'promo.paused': 'Promotion paused',
    'promo.activated': 'Promotion activated',
    'promo.newProductPromotionTitle': 'New Product Promotion',
    'promo.promotionTitle': 'Promotion Title',
    'promo.countryOptional': 'Country (leave empty for all countries)',
    'promo.allCountriesOption': 'All Countries',
    'promo.activePromotionsCount': '{n} active promotion(s)',
    'promo.activePromotionsHeading': 'Active Promotions',
    'promo.noActivePromotions': 'No active product promotions',
    'promo.createOneHint': 'Create one to offer deals in the shop',
    'promo.expiredInactiveHeading': 'Expired / Inactive Promotions',
    'promo.pausedBadge': 'Paused',
    'promo.confirmCancel': 'Confirm Cancel',
    'promo.no': 'No',
    'notifications.title': 'Notifications',
    'notifications.noNotifications': 'No notifications',
    'common.justNow': 'Just now',
    'common.minutesAgo': '{n}m ago',
    'common.hoursAgo': '{n}h ago',
    'common.daysAgo': '{n}d ago',
    'notifications.unreadCount': '{n} unread notification(s)',
    'notifications.allCaughtUp': 'All caught up!',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.tabAll': 'All',
    'notifications.tabUnread': 'Unread',
    'notifications.noUnread': 'No unread notifications',
    'notifications.emptyHint': "You'll receive notifications about meetings, promotions, and more",
    'notifications.viewDetails': 'View Details',
    'notifications.viewAll': 'View all notifications',
    'notifications.youreAllCaughtUp': "You're all caught up",
    'notifications.newBadge': '{n} new',
    'pv.totalEarned': 'Total Earned',
    'pv.totalSpent': 'Total Spent',
    'pv.subtitle': 'Track all your point value transactions',
    'pv.currentBalance': 'Current Balance',
    'pv.transactionHistory': 'Transaction History',
    'pv.noTransactions': 'No transactions yet',
    'pv.noTransactionsSubtitle': 'Your PV transaction history will appear here',
    'pv.type': 'Type',
    'pv.description': 'Description',
    'pv.amount': 'Amount',
    'pv.noDescription': 'No description',
    'pv.type.purchase': 'Purchase',
    'pv.type.meeting': 'Meeting',
    'pv.type.reward': 'Reward',
    'pv.type.bonus': 'Bonus',
    'pv.type.adjustment': 'Adjustment',
    'pv.type.refund': 'Refund',
  },
  fr: {
    'nav.overview': 'Apercu',
    'nav.shop': 'Boutique',
    'nav.cart': 'Panier',
    'nav.orders': 'Mes Commandes',
    'nav.team': 'Mon Equipe',
    'nav.pv': 'Historique PV',
    'nav.profile': 'Profil',
    'nav.notifications': 'Notifications',
    'nav.logout': 'Deconnexion',
    'nav.users': 'Utilisateurs',
    'nav.managers': 'Gestionnaires',
    'nav.products': 'Produits',
    'nav.inventory': 'Inventaire',
    'nav.orderManagement': 'Commandes',
    'nav.promotions': 'Promotions',
    'nav.approvals': 'Approbations',
    'nav.accounts': 'Comptes',
    'nav.deals': 'Offres',
    'nav.paymentSettings': 'Paiements',
    'nav.switchToUser': 'Passer en Vue Utilisateur',
    'nav.switchToAdmin': 'Passer en Vue Admin',
    'admin.dashboard': 'Tableau de Bord Admin',
    'admin.platformOverview': 'Apercu de la plateforme et indicateurs cles',
    'admin.totalUsers': 'Utilisateurs Total',
    'admin.active': 'actifs',
    'admin.totalPV': 'PV Total du Systeme',
    'admin.pendingOrders': 'Commandes en Attente',
    'admin.payments': 'Paiements (7 derniers jours)',
    'admin.systemStatus': 'Etat du Systeme',
    'admin.operational': 'Operationnel',
    'admin.welcome': 'Bienvenue sur le Tableau de Bord Admin',
    'admin.welcomeDesc': 'Gerez votre plateforme communautaire, approuvez les commandes et supervisez toutes les operations depuis ce hub central.',
    'admin.quickActions': 'Actions Rapides',
    'admin.approvals': 'Approbations',
    'admin.settings': 'Parametres',
    'admin.manageAccountsAction': 'Gerer les comptes utilisateurs',
    'admin.uploadProductsAction': 'Telecharger des produits via Excel',
    'admin.approvePendingOrdersAction': 'Approuver les commandes en attente',
    'admin.verifyPaymentProofsAction': 'Verifier les preuves de paiement',
    'admin.configurePaymentMethodsAction': 'Configurer les methodes de paiement',
    'admin.adjustSystemSettingsAction': 'Ajuster les parametres du systeme',
    'admin.monitorActivityLogsAction': 'Surveiller les journaux d\'activite',
    'user.dashboard': 'Tableau de Bord',
    'user.welcome': 'Bienvenue',
    'user.overviewSubtitle': 'Voici votre apercu communautaire',
    'user.totalPV': 'PV Total',
    'user.teamMembers': 'Membres de l\'Equipe',
    'user.pvNeeded': 'PV necessaires',
    'user.recentActivity': 'Activite Recente',
    'user.viewAll': 'Voir Tout',
    'user.noActivity': 'Aucune activite recente',
    'user.activeBranches': 'Branches Actives',
    'user.progressTo': 'Progression vers',
    'user.requiredPV': 'PV Requis',
    'user.requiredBranches': 'Branches Requises',
    'shop.title': 'Boutique',
    'shop.search': 'Rechercher des produits...',
    'shop.allCategories': 'Toutes les Categories',
    'shop.addToCart': 'Ajouter au Panier',
    'shop.outOfStock': 'Rupture de Stock',
    'shop.pv': 'PV',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.subtotal': 'Sous-total',
    'cart.total': 'Total',
    'cart.checkout': 'Commander',
    'cart.continueShopping': 'Continuer les Achats',
    'cart.remove': 'Supprimer',
    'orders.title': 'Mes Commandes',
    'orders.noOrders': 'Aucune commande',
    'orders.status': 'Statut',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.items': 'Articles',
    'orders.pending': 'En Attente',
    'orders.confirmed': 'Confirmee',
    'orders.shipped': 'Expediee',
    'orders.delivered': 'Livree',
    'orders.cancelled': 'Annulee',
    'team.title': 'Mon Equipe',
    'team.directRecruits': 'Recrutes Directs',
    'team.totalTeam': 'Equipe Totale',
    'team.noMembers': 'Aucun membre dans l\'equipe',
    'team.inviteCode': 'Votre Code d\'Invitation',
    'team.copyCode': 'Copier le Code',
    'team.copied': 'Copie!',
    'pv.title': 'Historique PV',
    'pv.total': 'PV Total',
    'pv.personal': 'PV Personnel',
    'pv.team': 'PV Equipe',
    'pv.noHistory': 'Aucun historique PV',
    'profile.title': 'Profil',
    'profile.fullName': 'Nom Complet',
    'profile.email': 'Email',
    'profile.phone': 'Telephone',
    'profile.country': 'Pays',
    'profile.save': 'Enregistrer',
    'profile.saving': 'Enregistrement...',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.forgotPassword': 'Mot de passe oublie?',
    'auth.noAccount': 'Pas de compte?',
    'auth.hasAccount': 'Deja un compte?',
    'auth.signUp': 'S\'inscrire',
    'auth.signIn': 'Se connecter',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succes',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.actions': 'Actions',
    'common.processing': 'Traitement...',
    'common.uploading': 'Telechargement...',
    'common.adding': 'Ajout...',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.inStock': 'En Stock',
    'common.na': 'N/A',
    'common.totalMembers': 'Membres Total',
    'common.copyId': 'Copier ID',
    'common.role': 'Role',
    'common.status': 'Statut',
    'common.user': 'Utilisateur',
    'common.admin': 'Admin',
    'common.manager': 'Gestionnaire',
    'common.placeOrder': 'Passer la Commande',
    'common.orderNow': 'Commander',
    'shop.subtitle': 'Achetez des produits et gagnez des points PV',
    'shop.noProducts': 'Aucun produit disponible dans cette categorie',
    'shop.priceNotSet': 'Prix non defini',
    'shop.unitPrice': 'Prix Unitaire',
    'shop.totalAmount': 'Montant Total',
    'shop.youSave': 'Vous economisez',
    'shop.orderPending': 'Votre commande sera en attente jusqu\'a approbation par le stockiste.',
    'shop.loading': 'Chargement des produits...',
    'shop.notAvailable': 'Non disponible',
    'shop.onlyLeft': 'Seulement {n} restant(s)',
    'shop.addedToCart': '{qty}x {name} ajoute(s) au panier!',
    'shop.failedAddToCart': "Echec de l'ajout au panier",
    'shop.priceNotAvailable': 'Prix non disponible pour votre pays',
    'shop.productNotAvailableCountry': 'Produit non disponible dans votre pays',
    'shop.onlyUnitsAvailable': 'Seulement {available} unites disponibles (besoin de {needed} dont {free} gratuit(s))',
    'shop.failedReserveStock': 'Echec de la reservation du stock: {message}',
    'shop.orderPlacedSuccess': 'Commande passee avec succes! La commande #{orderNumber} est en attente d\'approbation.',
    'shop.freeItemsIncludedSuffix': ' ({n} articles gratuits inclus!)',
    'shop.failedPlaceOrder': 'Echec de la commande',
    'shop.addMoreToGetFree': 'Ajoutez {n} de plus pour obtenir {free} gratuit(s)!',
    'shop.freeItemsIncluded': '+{n} article(s) gratuit(s) inclus!',
    'shop.quantity': 'Quantite',
    'shop.available': '{n} disponible(s)',
    'shop.pvPerUnit': '{pv} PV par unite',
    'shop.totalPVLabel': 'PV Total:',
    'shop.freeItemsLabel': 'Articles gratuits:',
    'cart.subtitle': 'Verifiez et finalisez vos articles selectionnes',
    'cart.emptySubtitle': 'Commencez vos achats pour ajouter des produits',
    'cart.orderSummary': 'Resume de la Commande',
    'cart.freeItems': 'Articles Gratuits',
    'cart.proceedCheckout': 'Proceder au Paiement',
    'cart.loading': 'Chargement du panier...',
    'cart.failedUpdateQty': 'Echec de la mise a jour de la quantite',
    'cart.itemRemoved': 'Article retire du panier',
    'cart.failedRemoveItem': "Echec de la suppression de l'article",
    'cart.priceNotAvailableFor': 'Prix non disponible pour {name}',
    'cart.failedSaveOrderItems': "Echec de l'enregistrement des articles de la commande: {message}",
    'cart.orderPlacedSuccessSimple': 'Commande {orderNumber} passee avec succes!',
    'cart.itemsCount': 'Articles ({n})',
    'cart.unitLabel': 'Unite:',
    'cart.checkoutModalTitle': 'Paiement',
    'cart.orderSummaryWithCount': 'Resume de la Commande ({n} articles)',
    'cart.freeShort': '+{n} gratuit(s)',
    'cart.totalCount': '({n} au total)',
    'orders.submitPaymentProof': 'Soumettre la Preuve de Paiement',
    'orders.paymentProofSubmitted': 'Preuve de Paiement Soumise',
    'orders.adminNotes': 'Notes Admin',
    'orders.totalOrders': 'Commandes Totales',
    'orders.totalAmount': 'Montant Total',
    'orders.awaitingPayment': 'En Attente de Paiement',
    'orders.subtitle': 'Suivez le statut et l\'historique de vos commandes',
    'orders.filterAll': 'Toutes',
    'orders.filterAwaiting': 'En attente',
    'orders.completed': 'Terminee',
    'orders.rejected': 'Rejetee',
    'orders.noStatusOrders': 'Aucune commande {status}',
    'orders.orderNumberLabel': 'Commande #{number}',
    'orders.itemsCountLabel': '{n} articles',
    'orders.statusApproved': 'Approuvee',
    'orders.qtyLabel': 'Qte: {n}',
    'orders.freeSuffix': ' (+{n} gratuit(s))',
    'orders.each': 'chacun',
    'orders.pvValue': 'Valeur PV',
    'orders.rejectionReason': 'Motif du Rejet:',
    'orders.pendingApprovalMsg': 'Votre commande est en attente d\'approbation par le stockiste.',
    'orders.approvedReserveMsg': 'Votre commande a ete approuvee et le stock a ete reserve. Veuillez envoyer le paiement et soumettre une preuve.',
    'orders.refOrderNumber': 'Ref: Commande #{number}',
    'orders.sendPaymentTo': 'Envoyer le paiement a',
    'orders.referenceOrderNumber': 'Reference: Commande #{number}',
    'orders.paymentBeingVerifiedMsg': 'Votre preuve de paiement a ete soumise et est en cours de verification par l\'admin.',
    'orders.submittedOn': 'Soumis le {date}',
    'orders.orderComplete': 'Commande Terminee!',
    'orders.paymentVerifiedMsg': 'Votre paiement a ete verifie et vos points PV ont ete ajoutes a votre compte.',
    'orders.orderNumberColon': 'Numero de Commande:',
    'orders.itemsColon': 'Articles:',
    'orders.paymentInstructionsTitle': 'Instructions de Paiement',
    'orders.transactionDetailsLabel': 'Details de la Transaction / Notes (Optionnel)',
    'orders.transactionPlaceholder': 'Entrez le numero de transaction, de confirmation, ou toute autre note...',
    'orders.paymentScreenshotLabel': 'Capture d\'ecran du Paiement *',
    'orders.changeScreenshot': 'Changer la Capture',
    'orders.uploadScreenshot': 'Telecharger la Capture de Paiement',
    'orders.uploadScreenshotHint': 'Veuillez telecharger une capture claire de votre confirmation de virement',
    'orders.paymentSubmittedToast': 'Preuve de paiement soumise avec succes! Vous serez notifie une fois verifiee.',
    'orders.failedSubmitPayment': 'Echec de la soumission de la preuve de paiement',
    'orders.paymentProofSubmittedMsg': 'Votre preuve de paiement pour la commande {orderNumber} a ete soumise et est en attente de verification.',
    'common.unknownProduct': 'Produit Inconnu',
    'profile.subtitle': 'Gerez vos informations personnelles et preferences',
    'profile.accountInfo': 'Informations du Compte',
    'profile.emailCantChange': 'L\'email ne peut pas etre modifie',
    'profile.memberSince': 'Membre Depuis',
    'profile.deliveryAddress': 'Adresse de Livraison',
    'profile.deliveryAddressDesc': 'Cette adresse sera utilisee pour la livraison lorsque vous passez une commande.',
    'profile.streetAddress': 'Adresse',
    'profile.apartment': 'Appartement, Suite, etc. (Optionnel)',
    'profile.city': 'Ville',
    'profile.stateProvince': 'Province / Etat',
    'profile.postalCode': 'Code Postal',
    'profile.importantNote': 'Note Importante:',
    'profile.countryChangeWarning': "Changer de pays affectera les produits que vous pouvez commander et la devise utilisee pour les transactions. Utile si vous voyagez ou demenagez dans un autre pays.",
    'profile.uploadPhoto': 'Cliquez pour telecharger',
    'profile.maxSize': 'Max 5Mo, JPG/PNG/GIF',
    'profile.selectCountry': 'Selectionnez un pays',
    'profile.currencyNote': 'Les produits seront affiches dans cette devise et vous commanderez depuis l\'inventaire de ce pays.',
    'profile.pageTitle': 'Parametres du Profil',
    'profile.phoneNumber': 'Numero de Telephone',
    'profile.countryColon': 'Pays:',
    'profile.currencyColon': 'Devise:',
    'profile.dangerZone': 'Zone Dangereuse',
    'profile.deleteAccountTitle': 'Supprimer votre compte',
    'profile.deleteAccountDesc': 'Supprimez definitivement votre compte et toutes les donnees associees. Cette action est irreversible.',
    'profile.deleteAccountBtn': 'Supprimer le Compte',
    'profile.changePassword': 'Changer le Mot de Passe',
    'profile.changePasswordDesc': 'Mettez a jour le mot de passe utilise pour vous connecter.',
    'profile.currentPassword': 'Mot de Passe Actuel',
    'profile.newPassword': 'Nouveau Mot de Passe',
    'profile.confirmNewPassword': 'Confirmer le Nouveau Mot de Passe',
    'profile.updatePasswordBtn': 'Mettre a Jour le Mot de Passe',
    'profile.passwordUpdated': 'Mot de passe mis a jour avec succes.',
    'profile.passwordMismatch': 'Les nouveaux mots de passe ne correspondent pas.',
    'profile.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caracteres.',
    'profile.currentPasswordIncorrect': 'Le mot de passe actuel est incorrect.',
    'profile.areYouSure': 'Etes-vous absolument certain?',
    'profile.deleteWarning1': 'Votre profil et votre historique PV seront definitivement supprimes',
    'profile.deleteWarning2': 'Les membres de votre equipe seront dissocies de votre compte',
    'profile.deleteWarning3': 'Toute commande en attente sera affectee',
    'profile.deleteWarning4': 'Cette action est irreversible',
    'profile.typeConfirmPrefix': 'Tapez',
    'profile.typeConfirmSuffix': 'pour confirmer',
    'profile.deletePlaceholder': 'Tapez DELETE ici...',
    'profile.deletingAccount': 'Suppression du compte...',
    'profile.permanentlyDelete': 'Supprimer definitivement mon compte',
    'profile.selectImageFile': 'Veuillez selectionner un fichier image',
    'profile.imageTooLarge': "L'image doit faire moins de 5 Mo",
    'profile.photoUpdated': 'Photo de profil mise a jour!',
    'profile.failedUploadImage': "Echec du telechargement de l'image",
    'profile.updateSuccess': 'Profil mis a jour avec succes!',
    'profile.failedUpdate': 'Echec de la mise a jour du profil',
    'profile.failedDeleteAccount': 'Echec de la suppression du compte',
    'profile.notAuthenticated': 'Non authentifie',
    'team.subtitle': 'Vos parrainages directs et leur progression',
    'team.referralLink': 'Votre Lien de Parrainage',
    'team.shareIdInfo': 'Partagez votre ID avec les nouveaux membres afin qu\'ils puissent vous ajouter comme parrain',
    'team.noMembersSubtitle': 'Construisez votre equipe en partageant votre lien de parrainage avec de nouveaux membres',
    'admin.userManagement': 'Gestion des Utilisateurs',
    'admin.manageUsers': 'Gerer tous les utilisateurs de la plateforme',
    'admin.searchUsers': 'Rechercher par nom ou email...',
    'admin.orderProcessing': 'Traitement des Commandes',
    'admin.paymentSubmitted': 'Paiement Soumis',
    'admin.verifyPayment': 'Verifiez la preuve de paiement. Confirmez ou rejetez.',
    'admin.loadingPending': 'Chargement des comptes en attente...',
    'admin.loadingOrders': 'Chargement des commandes...',
    'admin.loadingCodes': 'Chargement des codes...',
    'admin.loadingTeam': 'Chargement de la gestion d\'equipe...',
    'admin.loadingInventory': 'Chargement de l\'inventaire...',
    'admin.confirmRejection': 'Confirmer le Rejet',
    'admin.addManager': 'Ajouter un Gestionnaire',
    'admin.editPermissions': 'Modifier les Permissions',
    'admin.fullAccess': 'Acces Complet',
    'admin.addProduct': 'Ajouter un Produit',
    'admin.editProduct': 'Modifier le Produit',
    'admin.uploadImage': 'Telecharger une Image',
    'admin.editPromotion': 'Modifier la Promotion',
    'admin.createPromotion': 'Creer une Promotion',
    'admin.createFirstDeal': 'Creez votre premiere offre "Achetez X Obtenez Y Gratuit"',
    'admin.buyXGetYFree': 'Creez des offres "Achetez X Obtenez Y Gratuit"',
    'admin.expired': 'Expire',
    'admin.pause': 'Pause',
    'admin.activate': 'Activer',
    'admin.addInventory': 'Ajouter a l\'Inventaire',
    'admin.updating': 'Mise a jour...',
    'admin.productManagementTitle': 'Gestion des Produits',
    'admin.productManagementSubtitle': 'Gerer les produits et les valeurs PV',
    'admin.importExcel': 'Importer Excel',
    'admin.importing': 'Importation...',
    'admin.deleteSelected': 'Supprimer la Selection ({n})',
    'admin.productName': 'Nom du Produit',
    'admin.productType': 'Type de Produit',
    'admin.pvValue': 'Valeur PV',
    'admin.priceCAD': 'Prix (CAD)',
    'admin.productImage': 'Image du Produit',
    'admin.or': 'ou',
    'admin.enterImageUrl': "Entrez l'URL de l'image",
    'admin.description': 'Description',
    'admin.englishTranslationOptional': 'Traduction anglaise (optionnel)',
    'admin.imagePreview': "Apercu de l'Image:",
    'admin.activeProduct': 'Produit Actif',
    'admin.select': 'Selectionner',
    'admin.edit': 'Modifier',
    'admin.delete': 'Supprimer',
    'admin.productsDeleted': '{n} produit(s) supprime(s)',
    'admin.productsDeleteFailed': '{failed} echec(s), {deleted} supprime(s)',
    'admin.failedUpdateProduct': 'Echec de la mise a jour du produit',
    'admin.productUpdated': 'Produit mis a jour avec succes',
    'admin.productNameRequired': 'Le nom du produit est requis',
    'admin.failedUpdateMatchingProduct': 'Echec de la mise a jour du produit correspondant',
    'admin.productUpdatedLatest': 'Produit mis a jour avec les dernieres informations',
    'admin.failedAddProduct': 'Echec de l\'ajout du produit',
    'admin.productAdded': 'Produit ajoute avec succes',
    'admin.noValidProductsExcel': 'Aucun produit valide trouve dans le fichier Excel. Assurez-vous que les colonnes sont nommees: Product Name, Type, PV, Description',
    'admin.processedProducts': '{n} produit(s) traite(s) avec correspondance des doublons et mise a jour',
    'admin.errorProcessingExcel': 'Erreur lors du traitement du fichier Excel',
    'admin.failedDeleteProduct': 'Echec de la suppression du produit',
    'admin.productDeleted': 'Produit supprime',
    'admin.productNameEnglish': 'Nom du Produit (Anglais)',
    'admin.productTypeEnglish': 'Type de Produit / Categorie (Anglais)',
    'admin.descriptionEnglish': 'Description (Anglais)',
    'admin.optional': 'Optionnel',
    'admin.upload': 'Telecharger',
    'admin.enterUrl': "Entrez l'URL",
    'accounts.title': 'Approbations de Comptes',
    'accounts.subtitle': 'Examinez et approuvez les nouvelles inscriptions',
    'accounts.requireApproval': 'Approbation Requise',
    'accounts.requireApprovalOnDesc': 'Les nouveaux utilisateurs doivent etre approuves avant de se connecter',
    'accounts.requireApprovalOffDesc': 'Les nouveaux utilisateurs sont approuves automatiquement',
    'accounts.approvalEnabledToast': 'L\'approbation de compte est maintenant requise pour les nouvelles inscriptions.',
    'accounts.approvalDisabledToast': 'L\'approbation de compte n\'est plus requise. Les nouveaux utilisateurs seront approuves automatiquement.',
    'accounts.failedUpdateApprovalSetting': 'Echec de la mise a jour du parametre d\'approbation',
    'accounts.accountApprovedTitle': 'Compte Approuve!',
    'accounts.accountApprovedMsg': 'Votre compte a ete approuve. Vous pouvez maintenant vous connecter et commencer votre parcours bien-etre avec Life Changers.',
    'accounts.accountApprovedToast': 'Compte approuve avec succes!',
    'accounts.failedApproveAccount': "Echec de l'approbation du compte",
    'accounts.registrationNotApprovedTitle': "Inscription du Compte Non Approuvee",
    'accounts.registrationNotApprovedMsg': "Votre inscription n'a pas ete approuvee. Raison: {reason}",
    'accounts.accountRejectedToast': 'Compte rejete.',
    'accounts.failedRejectAccount': 'Echec du rejet du compte',
    'accounts.noPendingAccounts': 'Aucun compte en attente a examiner',
    'accounts.referredBy': 'Parraine Par',
    'accounts.registrationDate': "Date d'Inscription",
    'accounts.none': 'Aucun',
    'accounts.approve': 'Approuver',
    'accounts.reject': 'Rejeter',
    'accounts.rejectAccountTitle': 'Rejeter le Compte',
    'accounts.rejectReasonPrefix': 'Veuillez fournir une raison pour rejeter le compte de',
    'accounts.rejectReasonSuffix': ' :',
    'accounts.rejectionReasonLabel': 'Motif du Rejet*',
    'accounts.rejectionPlaceholder': 'Exemple: Informations incompletes, activite suspecte, compte en double...',
    'um.pv': 'PV',
    'um.demote': 'Retrograder',
    'um.promote': 'Promouvoir',
    'um.apply': 'Appliquer',
    'um.confirmDelete': 'Confirmer la Suppression',
    'um.deleting': 'Suppression...',
    'um.pvAmountPlaceholder': 'Montant PV (+ ou -)',
    'um.deleteConfirmPrefix': 'Etes-vous sur de vouloir supprimer definitivement le compte de',
    'um.deleteConfirmSuffix': " ? Toutes ses donnees seront supprimees et cette action est irreversible.",
    'um.invalidPvAmount': 'Veuillez entrer un montant PV valide',
    'um.failedAdjustPv': 'Echec de l\'ajustement du PV',
    'um.pvAdjusted': 'PV ajuste avec succes',
    'um.failedUpdateRole': 'Echec de la mise a jour du role',
    'um.userPromoted': 'Utilisateur promu avec succes',
    'um.userDemoted': 'Utilisateur retrograde avec succes',
    'um.failedDeleteUser': 'Echec de la suppression de l\'utilisateur',
    'um.userDeleted': 'Compte utilisateur supprime avec succes',
    'mgr.title': 'Gestion de l\'Equipe',
    'mgr.subtitle': 'Assignez des personnes pour gerer les commandes, l\'inventaire et plus',
    'mgr.searchManagers': 'Rechercher des gestionnaires...',
    'mgr.masterBadge': 'MAITRE',
    'mgr.permissionsCount': '{n} permissions',
    'mgr.fullAdminLabel': 'Admin Complet',
    'mgr.fullAdminDesc': 'A acces a toutes les fonctionnalites.',
    'mgr.permissionsLabel': 'Permissions',
    'mgr.noPermissionsAssigned': 'Aucune permission assignee',
    'mgr.promoteToAdmin': 'Promouvoir en Admin',
    'mgr.demoteToManager': 'Retrograder en Gestionnaire',
    'mgr.remove': 'Retirer',
    'mgr.noManagersFound': 'Aucun gestionnaire trouve',
    'mgr.selectUser': 'Selectionner un Utilisateur',
    'mgr.chooseUser': 'Choisissez un utilisateur...',
    'mgr.warningLabel': 'Avertissement:',
    'mgr.warningRemoveAll': 'Supprimer toutes les permissions retrogradera cette personne en utilisateur regulier.',
    'mgr.accessRestricted': 'Acces Restreint',
    'mgr.accessRestrictedDesc': 'Seul le compte maitre peut gerer les permissions de l\'equipe.',
    'mgr.pleaseSelectUserPermission': 'Veuillez selectionner un utilisateur et au moins une permission.',
    'mgr.failedAddManager': "Echec de l'ajout du gestionnaire",
    'mgr.permissionsUpdated': 'Permissions mises a jour avec succes',
    'mgr.failedUpdatePermissions': 'Echec de la mise a jour des permissions',
    'mgr.managerRemoved': 'Gestionnaire retire avec succes',
    'mgr.failedRemoveManager': 'Echec du retrait du gestionnaire',
    'mgr.userPromotedAdmin': 'Utilisateur promu admin',
    'mgr.failedPromoteAdmin': "Echec de la promotion en admin",
    'mgr.adminDemotedManager': 'Admin retrograde en gestionnaire',
    'mgr.failedDemoteAdmin': "Echec de la retrogradation de l'admin",
    'perm.manage_orders.label': 'Gerer les Commandes',
    'perm.manage_orders.desc': 'Voir, approuver, rejeter et mettre a jour le statut des commandes',
    'perm.manage_inventory.label': "Gerer l'Inventaire",
    'perm.manage_inventory.desc': 'Voir et mettre a jour les niveaux de stock',
    'perm.manage_users.label': 'Gerer les Utilisateurs',
    'perm.manage_users.desc': 'Voir et modifier les profils utilisateurs',
    'perm.manage_accounts.label': 'Gerer les Comptes',
    'perm.manage_accounts.desc': 'Approuver ou rejeter les nouvelles inscriptions',
    'perm.manage_products.label': 'Gerer les Produits',
    'perm.manage_products.desc': 'Ajouter, modifier et desactiver des produits',
    'perm.manage_promotions.label': 'Gerer les Promotions',
    'perm.manage_promotions.desc': 'Gerer les promotions et offres de produits',
    'ps.failedLoad': 'Echec du chargement des parametres de paiement',
    'ps.paymentMethodRemoved': 'Methode de paiement retiree',
    'ps.failedRemovePaymentMethod': 'Echec du retrait de la methode de paiement',
    'ps.presetExists': '"{label}" existe deja pour ce pays',
    'ps.paymentLabelRequired': 'Le libelle de paiement est requis pour toutes les methodes',
    'ps.settingsSavedFor': 'Parametres de paiement enregistres pour {country}',
    'ps.failedSaveSettings': 'Echec de l\'enregistrement des parametres de paiement',
    'ps.globalSettingsSaved': 'Parametres de paiement globaux enregistres',
    'ps.failedSaveGlobalSettings': 'Echec de l\'enregistrement des parametres globaux',
    'ps.loadingSettings': 'Chargement des parametres de paiement...',
    'ps.title': 'Parametres de Paiement',
    'ps.subtitle': 'Configurez les methodes de paiement et les informations de contact pour chaque pays',
    'ps.globalDefaults': 'Parametres par Defaut Globaux',
    'ps.globalDefaultsDesc': 'Utilises comme solution de secours lorsqu\'aucune information de paiement specifique au pays n\'est configuree.',
    'ps.defaultAdminEmail': 'Email Admin par Defaut',
    'ps.defaultPaymentInstructions': 'Instructions de Paiement par Defaut',
    'ps.generalInstructionsPlaceholder': 'Instructions de paiement generales...',
    'ps.saveGlobalSettings': 'Enregistrer les Parametres Globaux',
    'ps.filterByContinent': 'Filtrer par continent:',
    'ps.allCountries': 'Tous les Pays ({n})',
    'ps.activeMethods': '{n} methode(s) active(s)',
    'ps.noMethods': 'Aucune methode',
    'ps.quickAdd': 'Ajout rapide:',
    'ps.custom': 'Personnalise',
    'ps.noMethodsConfigured': 'Aucune methode de paiement configuree. Ajoutez-en une ci-dessus ou les utilisateurs verront le defaut global.',
    'ps.methodNumber': 'Methode #{n}',
    'ps.unsaved': 'Non enregistre',
    'ps.deactivate': 'Desactiver',
    'ps.activate': 'Activer',
    'ps.remove': 'Retirer',
    'ps.paymentLabel': 'Libelle de Paiement *',
    'ps.paymentLabelPlaceholder': 'ex. Interac e-Transfer, MTN Mobile Money',
    'ps.recipientName': 'Nom du Destinataire',
    'ps.recipientNamePlaceholder': 'Nom du destinataire',
    'ps.recipientContact': 'Contact du Destinataire (email, telephone, ou numero de compte)',
    'ps.recipientContactPlaceholder': 'ex. admin@email.com ou +237 6XX XXX XXX',
    'ps.methodKey': 'Cle de Methode',
    'ps.methodKeyPlaceholder': 'ex. e_transfer, mtn_mobile_money',
    'ps.paymentInstructions': 'Instructions de Paiement',
    'ps.paymentInstructionsPlaceholder': 'Instructions specifiques pour cette methode de paiement...',
    'ps.saveCountrySettings': 'Enregistrer les Parametres pour {country}',
    'inv.title': "Gestion de l'Inventaire",
    'inv.subtitle': 'Gerer les niveaux de stock des produits',
    'inv.setDefaultStock': 'Definir le Stock par Defaut',
    'inv.addInventory': "Ajouter a l'Inventaire",
    'inv.searchProducts': 'Rechercher des produits...',
    'inv.noItemsFound': 'Aucun article en inventaire trouve',
    'inv.product': 'Produit',
    'inv.available': 'Disponible',
    'inv.reserved': 'Reserve',
    'inv.lowStock': 'Stock Faible',
    'inv.addProductInventoryTitle': "Ajouter l'Inventaire du Produit",
    'inv.selectProduct': 'Selectionnez un produit',
    'inv.stockAvailable': 'Stock Disponible',
    'inv.lowStockThreshold': 'Seuil d\'Alerte de Stock Faible',
    'inv.refreshStock': 'Actualiser le Stock',
    'inv.reservedHeldByOrders': 'Reserve (retenu par des commandes en attente)',
    'inv.resetToZero': 'Reinitialiser a 0',
    'inv.reservedHint': "Diminuez ceci uniquement si des commandes ont ete rejetees/annulees et que le stock n'a pas ete correctement libere.",
    'inv.availableForSale': 'Disponible a la vente',
    'inv.updateAcrossProducts': 'Mettre a jour les niveaux de stock pour tous les produits.',
    'inv.overwriteWarning': 'Ceci ecrasera les niveaux de stock actuels pour la portee selectionnee.',
    'inv.updating': 'Mise a jour...',
    'inv.updateExistingStock': 'Mettre a Jour le Stock Existant',
    'inv.initializing': 'Initialisation...',
    'inv.initializeAllProducts': 'Initialiser Tous les Produits',
    'inv.inventoryAdded': 'Inventaire ajoute avec succes',
    'inv.failedAddInventory': "Echec de l'ajout de l'inventaire",
    'inv.stockReservedError': 'Le stock disponible ne peut pas etre inferieur au stock reserve. Diminuez "Reserve" ou augmentez "Stock Disponible" d\'abord.',
    'inv.inventoryUpdated': 'Inventaire mis a jour avec succes',
    'inv.failedUpdateInventory': "Echec de la mise a jour de l'inventaire",
    'inv.stockUpdatedToAll': 'Stock mis a jour a {n} pour tous les produits',
    'inv.initializedRecords': '{n} enregistrements d\'inventaire initialises avec {qty} de stock chacun',
    'inv.failedInitializeStock': 'Echec de l\'initialisation du stock',
    'promo.title': 'Promotions Produits',
    'promo.newPromotion': 'Nouvelle Promotion',
    'promo.pleaseAllFields': 'Veuillez remplir tous les champs requis. Les quantites d\'achat et gratuites doivent etre d\'au moins 1.',
    'promo.failedCreate': 'Echec de la creation de la promotion',
    'promo.selectedProductFallback': 'Produit selectionne',
    'promo.created': 'Promotion creee avec succes',
    'promo.failedUpdate': 'Echec de la mise a jour de la promotion',
    'promo.updated': 'Promotion mise a jour avec succes',
    'promo.failedCancel': 'Echec de l\'annulation de la promotion',
    'promo.cancelled': 'Promotion annulee et terminee',
    'promo.failedDelete': 'Echec de la suppression de la promotion',
    'promo.deleted': 'Promotion supprimee',
    'promo.noPromotionsYet': 'Aucune promotion pour le moment',
    'promo.titleLabel': 'Titre',
    'promo.titlePlaceholder': 'ex., Achetez 3 Obtenez 1 Gratuit',
    'promo.buyQuantity': 'Quantite a Acheter',
    'promo.buyQuantityHint': 'Le client doit acheter cette quantite',
    'promo.freeQuantity': 'Quantite Gratuite',
    'promo.freeQuantityHint': 'Ils recoivent cette quantite gratuitement',
    'promo.startsAt': 'Debute Le',
    'promo.endsAt': 'Se Termine Le',
    'promo.previewText': 'Apercu: Achetez {buy}, obtenez {free} gratuit(s) (le client paie pour {buy}, recoit {total} au total)',
    'promo.payReceiveTotal': 'Paie pour {buy}, recoit {total} au total',
    'promo.starts': 'Debut:',
    'promo.ends': 'Fin:',
    'common.close': 'Fermer',
    'om.failedLoadUserHistory': "Echec du chargement de l'historique des commandes",
    'om.cannotApproveStock': "Impossible d'approuver: stock insuffisant pour {product}.",
    'om.orderApprovedToast': 'Commande approuvee. Stock reserve. L\'utilisateur a ete notifie de soumettre le paiement.',
    'om.failedApproveOrder': "Echec de l'approbation de la commande",
    'om.ordersMergedToast': '{n} commande(s) fusionnee(s) dans {orderNumber}. Approbation en cours...',
    'om.failedMergeOrders': 'Echec de la fusion des commandes',
    'om.orderRejectedToast': "Commande rejetee. L'utilisateur a ete notifie.",
    'om.failedRejectOrder': 'Echec du rejet de la commande',
    'om.paymentVerifiedToast': "Paiement verifie et commande terminee! L'utilisateur a ete notifie.",
    'om.failedVerifyPayment': 'Echec de la verification du paiement',
    'om.paymentRejectedToast': "Preuve de paiement rejetee. L'utilisateur a ete notifie de la soumettre a nouveau.",
    'om.failedRejectPayment': 'Echec du rejet du paiement',
    'om.statusChangedToast': 'Statut de la commande change a "{status}".',
    'om.failedChangeStatus': 'Echec du changement de statut',
    'om.promotionAppliedTitle': 'Promotion Appliquee!',
    'om.promotionAppliedMsg': 'Vous avez beneficie d\'une promotion sur {product}! {n} article(s) gratuit(s) ajoute(s) a la commande {orderNumber}.',
    'om.orderApprovedTitle': 'Commande Approuvee - Paiement Requis',
    'om.orderApprovedMsg': 'Votre commande {orderNumber} a ete approuvee. Veuillez envoyer le paiement a {email} et soumettre votre preuve de paiement.',
    'om.orderRejectedNotifTitle': 'Commande Rejetee',
    'om.orderRejectedMsg': 'Votre commande {orderNumber} a ete rejetee. Raison: {reason}',
    'om.paymentVerifiedTitle': 'Paiement Verifie - Commande Terminee!',
    'om.paymentVerifiedMsg': 'Votre paiement pour la commande {orderNumber} a ete verifie. Vous avez gagne {pv} PV!',
    'om.paymentRejectedTitle': 'Preuve de Paiement Rejetee',
    'om.paymentRejectedMsg': 'Votre preuve de paiement pour la commande {orderNumber} a ete rejetee. Raison: {reason}. Veuillez soumettre une nouvelle preuve de paiement.',
    'om.statusUpdatedTitle': 'Statut de la Commande Mis a Jour',
    'om.statusUpdatedMsg': 'Le statut de votre commande {orderNumber} a ete change a: {status}.',
    'om.title': 'Gestion des Commandes',
    'om.subtitle': 'Examiner et approuver les commandes des clients',
    'om.awaitingConfirmationBanner': '{n} commande(s) en attente de confirmation de paiement',
    'om.notShownInPendingFilter': ' (non affichee dans le filtre "En Attente" actuel)',
    'om.viewArrow': 'Voir',
    'om.workflowTitle': 'Flux de Traitement des Commandes',
    'om.step1Desc': 'L\'utilisateur soumet une commande. Verifiez le stock et approuvez/rejetez.',
    'om.step2Desc': 'Stock reserve. L\'utilisateur envoie le paiement a l\'email admin.',
    'om.step4Desc': 'Paiement verifie. Les PV sont attribues a l\'utilisateur.',
    'om.workflowImportantNote': 'Important: Approuver une commande reserve le stock et envoie votre email comme adresse de paiement. Les PV ne sont attribues QUE lors de la verification du paiement.',
    'om.noOrdersFoundTitle': 'Aucune Commande Trouvee',
    'om.noPendingOrders': 'Aucune commande en attente pour le moment.',
    'om.noAwaitingPaymentOrders': 'Aucune commande en attente de paiement.',
    'om.noCompletedOrders': 'Aucune commande terminee pour le moment.',
    'om.noOrdersSystem': 'Aucune commande dans le systeme pour le moment. Les commandes apparaitront ici lorsque les utilisateurs commenceront a acheter.',
    'om.searchOrdersPlaceholder': 'Rechercher des commandes...',
    'om.allStatus': 'Tous les Statuts ({n})',
    'om.noOrdersFoundSimple': 'Aucune commande trouvee',
    'om.orderNumberCol': 'Commande #',
    'om.customer': 'Client',
    'om.products': 'Produits',
    'om.viewAllOrdersFromUser': 'Voir toutes les commandes de cet utilisateur',
    'om.proof': 'Preuve',
    'om.view': 'Voir',
    'om.verify': 'Verifier',
    'om.changeStatus': 'Changer le Statut',
    'om.orderDetailsTitle': 'Details de la Commande',
    'om.orderNumberLabel': 'Numero de Commande',
    'om.orderItems': 'Articles de la Commande',
    'om.orderDateLabel': 'Date de la Commande',
    'om.noAddressWarning': "Avertissement: Le client n'a pas encore fourni d'adresse de livraison. Veuillez le contacter pour mettre a jour son profil avant l'expedition.",
    'om.paymentProof': 'Preuve de Paiement',
    'om.loadingProof': 'Chargement de la preuve...',
    'om.clickToViewFull': "Cliquez sur l'image pour l'agrandir",
    'om.submittedLabel': 'Soumis:',
    'om.customerNotesLabel': 'Notes du Client:',
    'om.verifiedLabel': 'Verifie:',
    'om.rejectionReasonLabel': 'Motif du Rejet',
    'om.orderWord': 'Commande',
    'om.fromWord': 'de',
    'om.otherPendingOrdersHeading': '{n} autre(s) commande(s) en attente de cet utilisateur',
    'om.selectOrdersToMerge': 'Selectionnez les commandes ci-dessous pour les fusionner en une seule commande combinee avant approbation.',
    'om.deselectAll': 'Tout deselectionner',
    'om.selectAll': 'Tout selectionner',
    'om.combinedTotalAfterMerge': 'Total combine apres fusion:',
    'om.adminNotesOptional': 'Notes Admin (Optionnel)',
    'om.addNotesApprovalPlaceholder': 'Ajoutez des notes sur cette approbation...',
    'om.mergeAndApprove': 'Fusionner ({n} commandes) et Approuver',
    'om.approveThisOrderOnly': 'Approuver Uniquement Cette Commande',
    'om.rejectOrderTitle': 'Rejeter la Commande',
    'om.rejectReasonPromptPrefix': 'Veuillez fournir une raison pour rejeter la commande',
    'om.rejectReasonPlaceholder': 'Expliquez pourquoi cette commande est rejetee...',
    'om.internalNotesPlaceholder': 'Ajoutez des notes internes...',
    'om.verifyPaymentTitle': 'Verifier le Paiement',
    'om.paymentNotesFromCustomer': 'Notes de Paiement du Client',
    'om.paymentScreenshotPlain': 'Capture d\'ecran du Paiement',
    'om.verifyImportantNote': 'Important: Veuillez verifier que le montant du paiement correspond au total de la commande et que le paiement a ete recu avant de confirmer.',
    'om.verifyAndComplete': 'Verifier le Paiement et Terminer la Commande',
    'om.rejectPaymentProofTitle': 'Rejeter la Preuve de Paiement',
    'om.rejectPaymentReasonPrompt': 'Veuillez fournir une raison pour rejeter la preuve de paiement de la commande',
    'om.rejectPaymentPlaceholder': "Exemple: La capture d'ecran du paiement n'est pas claire, le montant ne correspond pas, paiement non recu...",
    'om.rejectPaymentProofBtn': 'Rejeter la Preuve de Paiement',
    'om.changeOrderStatusTitle': 'Changer le Statut de la Commande',
    'om.currentStatus': 'Statut Actuel',
    'om.newStatus': 'Nouveau Statut',
    'om.statusChangeNote': 'Remarque: Changer manuellement le statut ne declenchera pas les ajustements de stock ou de PV. Utilisez le flux normal d\'approbation/verification pour cela.',
    'om.updateStatusBtn': 'Mettre a Jour le Statut',
    'om.orderHistoryTitle': 'Historique des Commandes - {name}',
    'om.totalOrdersCount': '{n} commande(s) au total',
    'om.totalSpentLabel': 'Total Depense: {currency} {amount}',
    'om.noOrdersForUser': 'Aucune commande trouvee pour cet utilisateur',
    'om.paidLabel': 'Paye',
    'om.approveOrderTitle': 'Approuver la Commande',
    'notif.newAccountRequestTitle': "Nouvelle Demande d'Approbation de Compte",
    'notif.newAccountRequestMsg': '{name} ({email}) s\'est inscrit et est en attente d\'approbation.',
    'notif.newPromotionTitle': 'Nouvelle Promotion Disponible',
    'notif.newPromotionMsg': '{label} est maintenant active pour {product}.',
    'notif.newOrderPlacedTitle': 'Nouvelle Commande Passee',
    'notif.newOrderPlacedMsg': 'La commande #{orderNumber} de {userName} necessite une approbation',
    'notif.orderReceivedTitle': 'Commande Recue',
    'notif.orderReceivedMsg': 'Votre commande #{orderNumber} a ete recue et est en attente d\'approbation.',
    'notif.paymentSubmittedAdminMsg': 'Commande #{orderNumber} - {userName} a soumis une preuve de paiement',
    'promo.pageTitle': 'Promotions',
    'promo.manageDeals': 'Gerer les offres de produits',
    'promo.pleaseAllFieldsSimple': 'Veuillez remplir tous les champs requis.',
    'promo.paused': 'Promotion mise en pause',
    'promo.activated': 'Promotion activee',
    'promo.newProductPromotionTitle': 'Nouvelle Promotion Produit',
    'promo.promotionTitle': 'Titre de la Promotion',
    'promo.countryOptional': 'Pays (laissez vide pour tous les pays)',
    'promo.allCountriesOption': 'Tous les Pays',
    'promo.activePromotionsCount': '{n} promotion(s) active(s)',
    'promo.activePromotionsHeading': 'Promotions Actives',
    'promo.noActivePromotions': 'Aucune promotion de produit active',
    'promo.createOneHint': 'Creez-en une pour offrir des offres dans la boutique',
    'promo.expiredInactiveHeading': 'Promotions Expirees / Inactives',
    'promo.pausedBadge': 'En Pause',
    'promo.confirmCancel': "Confirmer l'Annulation",
    'promo.no': 'Non',
    'notifications.title': 'Notifications',
    'notifications.noNotifications': 'Aucune notification',
    'common.justNow': "A l'instant",
    'common.minutesAgo': 'Il y a {n}min',
    'common.hoursAgo': 'Il y a {n}h',
    'common.daysAgo': 'Il y a {n}j',
    'notifications.unreadCount': '{n} notification(s) non lue(s)',
    'notifications.allCaughtUp': 'Tout est a jour!',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.tabAll': 'Toutes',
    'notifications.tabUnread': 'Non lues',
    'notifications.noUnread': 'Aucune notification non lue',
    'notifications.emptyHint': 'Vous recevrez des notifications sur les reunions, promotions et plus encore',
    'notifications.viewDetails': 'Voir les Details',
    'notifications.viewAll': 'Voir toutes les notifications',
    'notifications.youreAllCaughtUp': 'Vous etes a jour',
    'notifications.newBadge': '{n} nouvelle(s)',
    'pv.totalEarned': 'Total Gagne',
    'pv.totalSpent': 'Total Depense',
    'pv.subtitle': 'Suivez toutes vos transactions de points de valeur',
    'pv.currentBalance': 'Solde Actuel',
    'pv.transactionHistory': 'Historique des Transactions',
    'pv.noTransactions': 'Aucune transaction pour le moment',
    'pv.noTransactionsSubtitle': 'Votre historique de transactions PV apparaitra ici',
    'pv.type': 'Type',
    'pv.description': 'Description',
    'pv.amount': 'Montant',
    'pv.noDescription': 'Aucune description',
    'pv.type.purchase': 'Achat',
    'pv.type.meeting': 'Reunion',
    'pv.type.reward': 'Recompense',
    'pv.type.bonus': 'Bonus',
    'pv.type.adjustment': 'Ajustement',
    'pv.type.refund': 'Remboursement',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'fr' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const template = translations[language][key] || key;
    if (!params) return template;
    return Object.entries(params).reduce(
      (result, [paramKey, value]) => result.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(value)),
      template
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
